### ISSUE TITLE
React Native Init doesn't work for TVOS

### ISSUE THREAD

**Issue by omrip2** [react-native-community/react-native-tvos#5]
When creating new project with the following command the xcode project doesn't being compiled to tvOS:
react-native init TestApp --version=react-native@npm:react-native-tvos@0.60.4-0
The error which being thrown by xcode is library not found for -lPods-projectName-tvOS

React Native version:
System:
    OS: macOS 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 9.14 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    npm: 6.10.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1

## Steps To Reproduce

1. Install react-native
2. run the command react-native init TestApp --version=react-native@npm:react-native-tvos@0.60.4-0
3. cd project/ios
4. pod install
5. Open Xcode workspace
6. change to tvOS and build

Error: library not found for -lPods-projectName-tvOS

Describe what you expected to happen:
The project should be compiled to tvOS

**Comment by dlowder-salesforce** [comment]
Confirmed -- issue reproduces on react-native-tvos@0.60.4-1.

It appears that the new cocoapods-based template files don't support tvOS.  (The non-cocoapods templates from 0.59 do work with tvOS).

Investigating.

**Comment by dlowder-salesforce** [comment]
@omrip2 I just merged the fix for this into the 0.60.4 branch.  You should be able to verify the fix yourself as follows:

```js
react-native init TestAppFix --version=react-native@https://github.com/react-native-community/react-native-tvos#tvos-v0.60.4
open TestAppFix/ios/TestAppFix.xcworkspace/
```

and then build and run the TestAppFix-tvOS target.  Please let me know if this is working for you, then I'll push out a patch release.

**Comment by dlowder-salesforce** [comment]
This is now fixed and released in https://github.com/react-native-community/react-native-tvos/releases/tag/v0.60.4-2

**Comment by mtshv** [comment]
@dlowder-salesforce Thank you!
Btw, I've noticed that readme still uses 0.60.4-1

**Comment by mikehardy** [comment]
The readme still references 0.60.4-0 I think?

I'm the react-native-device-info maintainer and I'm trying to test a PR that fixes tvOS support there - https://github.com/react-native-community/react-native-device-info/pull/781

But when I run `react-native init exampletvOS --version=react-native@npm:react-native-tvos@0.60.4-2` I get:

```
✖ Downloading template
error Error: Command failed: yarn add react-native@react-native@npm:react-native-tvos@0.60.4-2
error Couldn't find any versions for "react-native" that matches "react-native@npm:react-native-tvos@0.60.4-2"
yarn add v1.17.3
info No lockfile found.
[1/4] Resolving packages...
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

help? :-)

**Comment by dlowder-salesforce** [comment]
Please try 0.60.4-5

**Comment by mikehardy** [comment]
I still get this
```
error Couldn't find any versions for "react-native" that matches "react-native@npm:react-native-tvos@0.60.4-5"
```

It appears to not even be downloading the template, so I don't think -0 or -4 or -5 is the problem, it's something more fundamental. Likely something trivial I'm missing?

What commands would you run in exact order to start from nothing and have a test app called 'exampletvOS' ?

I'd assumed it was just that `react-native init exampletvOS --version=react-native@npm:react-native-tvos@0.60.4-5` but maybe there is something more?

Maybe it's a CLI issue?
```
(virtualenv) mike@kunashir:~/work/react-random/react-native-device-info (master) % react-native -v
react-native-cli: 2.0.1
react-native: 0.60.5
```

I appreciate the time helping, hopefully it force-multiplies in the form of good tvOS support for react-native-device-info

**Comment by dlowder-salesforce** [comment]
Maybe there is an issue because you are executing `react-native init TestApp --version=react-native@npm:react-native-tvos@0.60.4-5` inside an existing RN directory.  The command works for me.....

**Comment by mikehardy** [comment]
@dlowder-salesforce you nailed it. The CLI won't tolerate being in a directory with node_modules already I suppose. Similar to monorepos etc I guess you need an intermediate directory. Thanks

**Comment by mikehardy** [comment]
<img width="1484" alt="Window 2019-09-15 at 09 45 05" src="https://user-images.githubusercontent.com/782704/64923245-a9cafa80-d79d-11e9-85a2-fe3e8d855b08.png">

🚀
